# (1)defining which docker container to use
box: maven
build:
  steps:
    # (2) a build step
    - xenoterracide/maven:
        goals: clean package -DskipTests
        version: 3.5.2
    - script:
        name: copy package to output
        # (3) copy artefact to output
        code: |
          cp ./target/*.war $WERCKER_OUTPUT_DIR/oms.war
# (4) create an name for that pipeline
deploy:
  # (5) configure the container
services:
tomcat:
    image: tomcat:7.0
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
        - 8888:8080
    container_name: tomcat7
    volumes:
        - ./tomcat7:/usr/local/tomcat:rw
    entrypoint: /bin/bash /usr/local/tomcat/bin/startup.sh
    tty: true
steps:
    # (6) moving our artifact to the final location
    - script:
      code: |
        mv $WERCKER_SOURCE_DIR/oms.war /oms.war
        touch /oms.war
    # (7) pushing the container to Docker Hub
    - internal/docker-push:
        # (8) that is defined in the wercker console as protected environment variables
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
        tag: latest
        repository: $DOCKER_REPOSITORY
     - script:
       code: |
        touch  $WERCKER_OUTPUT_DIR/deploy
